### ISSUE TITLE
I am unable to find an equivalent off-chain library for building a SMT that is compatible with the on-chain version

### ISSUE THREAD

**Issue by andrea-rizzini** [dl-solarity/solidity-lib#117]
### Describe the feature

I’ve been using this library: https://github.com/privacy-scaling-explorations/zk-kit/tree/main/packages/smt, but it generates a different root hash, so I assume it is not compatible with your optimizations. Is there an off-chain library that’s compatible with your on-chain SMT implementation?

**Comment by Arvolear** [comment]
Hey @andrea-rizzini, thanks for opening this issue. [This JS library](https://github.com/iden3/js-merkletree) from iden3 is compatible with our implementation. However, their `delete` operation may still have some discrepancies as their test coverage is very poor.

Regardless, we'll take a look at the zk-kit approach and get back to you.

**Comment by andrea-rizzini** [comment]
Are you sure that one is compatible? Looking at the test;[]( https://github.com/iden3/js-merkletree/blob/main/tests/full.test.ts) line 116 I found:
`const inputs = [BigInt('100'), BigInt('200'), BigInt('1')];`
But on your documentation [](https://docs.solarity.dev/docs/getting-started/guides/libs/data-structures/sparse-merkle-tree) you states this: H(1 || k || v)
Is the domain separator inverted?

**Comment by Arvolear** [comment]
It is definitely compatible. This must be a typo in the documentation, will fix it, thanks for noticing.

**Comment by andrea-rizzini** [comment]
Ook thanks, just asked before trying.

**Comment by andrea-rizzini** [comment]
There was a mismatch in hashers I was using, you can close the issue. Thanks for the support
